const BOOK_COLLECTION = 'book';
const COMMENT_COLLECTION = 'comment';
const USER_COLLECTION = 'user';
const USER_BOOKS_COLLECTION = 'userBooks';

export default { BOOK_COLLECTION, COMMENT_COLLECTION, USER_COLLECTION, USER_BOOKS_COLLECTION };